# Generated by Django 3.2.4 on 2021-07-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceInfo',
            fields=[
                ('info_about_place', models.TextField(max_length=500)),
                ('place_name', models.TextField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='uploads/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.placeinfo')),
            ],
        ),
    ]
